source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

use_frameworks!

target 'WelcomeViewController_Example' do
  pod 'WelcomeViewController', :path => '../'

  target 'WelcomeViewController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.0'
    pod 'Nimble', '~> 8.0'
  end
end
