source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

use_frameworks!

target 'WelcomeViewController_Example' do
  pod 'WelcomeViewController', :path => '../'

  target 'WelcomeViewController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
