source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '17.0'

use_frameworks!

target 'WelcomeViewController_Example' do
  pod 'WelcomeViewController', :path => '../'

  target 'WelcomeViewController_Tests' do
    inherit! :search_paths
  end
end
